### PR TITLE
Fix shimMode default inside worker

### LINKED ISSUE #524: Shim mode is no longer correctly determined inside worker
The README claims: "By default, when there is no DOM present, ES Module Shims will switch into shim mode". 

This seems to have been correct up to #269, where the conditional now always checks the init options or (if present) the document queries. Previously this had a ternary defaulting to `true` if no document was present.

### PR DESCRIPTION
**Pull request by fvanderveen**
Fixes #524, by reintroducing the `true` default if there is no document.

### CODE REVIEW

File: src/env.js [hunk 1]
```diff
@@ -35,9 +35,10 @@ if (self.importShim || (r && r !== version)) {
 // shim mode is determined on initialization, no late shim mode
 export const shimMode =
   esmsInitOptions.shimMode ||
-  (hasDocument &&
+  (hasDocument ?
     document.querySelectorAll('script[type=module-shim],script[type=importmap-shim],link[rel=modulepreload-shim]')
-      .length > 0);
+      .length > 0
+  : true);
```
Comment (guybedford) [inline src/env.js:41]:
```suggestion
  // Without a document, shim mode is always true as we cannot polyfill
  : true);
```

**Review by guybedford — APPROVED** [review]
Thanks for finding this - just important to add a comment given there is no test so we don't regress again.

**Comment by guybedford** [comment]
Thanks for the ping, yes only have limited time for OSS work here.
