### PR TITLE
fix: self imports.

### LINKED ISSUE #295: ESM self-import: different behaviors between shim and browser native modes
Hi, thanks for this great project that enables us to use import-maps in production.

Recently we run into a tricky issue. When creating ESM bundles using latest Webpack 5, there's some self-import code at the bottom of entry ESM file. The bundles work well in latest Chrome, however they fail to initialize when handled in shim mode.

I've made a minimal example to reproduce this. Below is the JS part, the complete example is uploaded to https://gist.github.com/evisong/0e70d3ee5215d751e7d57d8378de9c96.

```js
export const b = {
  m: () => console.log('Run m')
};

import { b as c } from './module-self-import.mjs';

const m = c.m;

export default function a() {
  console.log('Run a');
  m();
}
```

In native mode, the browser console shows:

```
Run inline
Run a
Run m
```

However in shim mode, the browser console prompts an error:

```
module.mjs:7 Uncaught TypeError: Cannot read properties of undefined (reading 'm')
    at module.mjs:7:13
```

To workaround this blocking issue, we have to disable shim mode, so we temporarily inline es module URLs instead of using elegant importmaps.

I'm not sure if this is a common use case since I've only seen it in Webpack generated bundles. Could you share some guidance? Thanks.

### PR DESCRIPTION
**Pull request by tommie**
Upgrades to es-module-lexer 1.0.0. For returning exports as ExportSpecifier[].

Based on @guybedford's #296.

Closes #295.

### CODE REVIEW

File: src/es-module-shims.js [hunk 1]
```diff
@@ -306,6 +306,12 @@ function resolveDeps (load, seen) {
       }
     }
 
+    // support progressive cycle binding updates
+    if (load.s) {
+      const fields = exports.filter(expt => expt.n !== 'default' && expt.ln).map(expt => `${expt.n}: ${expt.ln}`);
```
Comment (guybedford) [inline src/es-module-shims.js:311]: Rather than `${expt.n}:` we should use the same form as the original exported identifier - `${source.slice(expt.s, expt.e)}` to also support string exports. We also don't actually need a default filter here since `expt.ln` is always guaranteed to be a valid identifier now:

```suggestion
      const fields = exports.filter(expt => expt.ln).map(expt => `${source.slice(expt.s, expt.e)}: ${expt.ln}`);
```

File: src/es-module-shims.js [hunk 2]
```diff
@@ -269,11 +269,11 @@ function resolveDeps (load, seen) {
...
             blobUrl = depLoad.s = createBlob(`export function u$_(m){${
               depLoad.a[1].map(
-                name => name === 'default' ? `d$_=m.default` : `${name}=m.${name}`
+                expt => expt.n === 'default' ? `d$_=m.default` : `${expt.n}=m.${expt.n}`
               ).join(',')
             }}${
-              depLoad.a[1].map(name =>
-                name === 'default' ? `let d$_;export{d$_ as default}` : `export let ${name}`
+              depLoad.a[1].map(expt =>
+                expt.n === 'default' ? `let d$_;export{d$_ as default}` : `export let ${expt.n}`
```
Comment (guybedford) [inline src/es-module-shims.js:276]: I wonder if we can update this to properly support string exports now / non identifier exports in general rather than just default?

One way would be to number all identifiers (`e$1`, `e$2`, ...) and then export a bag - `export { e$1 as ${source.slice(expt.s, expt.e)}, ... }` kind of thing. Let me know if that makes sense?

**Review by guybedford — COMMENTED** [review]
Thanks for the update, will be great to land this!

File: src/es-module-shims.js (hunk 1 above)
Comment (tommie) [reply src/es-module-shims.js]: Nice!

File: src/es-module-shims.js (hunk 2 above)
Comment (tommie) [reply src/es-module-shims.js]: Done. We already have the local name, so I don't think we need to generate identifiers.

The two cyclic test cases now create:

```js
export function u$_(m){f=m.f,d$_=m.default}let f;let d$_;export {f as f,d$_ as default}
//# sourceURL=http://localhost:8088/test/fixtures/test-circular1.js?cycle

export function u$_(m){b=m.b,c=m.d,e=m['e f'],d$_=m.default}let b;let c;let e;let d$_;export {b as b,c as d,e as 'e f',d$_ as default}
//# sourceURL=http://localhost:8088/test/fixtures/test-self-import.js?cycle
```

File: src/es-module-shims.js [hunk 3]
```diff
@@ -267,15 +267,23 @@ function resolveDeps (load, seen) {
...
-                name => name === 'default' ? `d$_=m.default` : `${name}=m.${name}`
+                expt => expt.ln ? `${expt.ln}=m${dotOrBracketAccessor(expt)}` : `d$_=m.default`
               ).join(',')
             }}${
-              depLoad.a[1].map(name =>
-                name === 'default' ? `let d$_;export{d$_ as default}` : `export let ${name}`
-              ).join(';')
-            }\n//# sourceURL=${depLoad.r}?cycle`);
+              depLoad.a[1].map(
+                expt => expt.ln ? `let ${expt.ln};` : 'let d$_;'
```
Comment (guybedford) [inline src/es-module-shims.js:280]: I think we should just skip bindings entirely if there is no local name, as in we can filter them out first.

File: src/es-module-shims.js [hunk 4]
```diff
@@ -267,15 +267,23 @@ function resolveDeps (load, seen) {
...
+              ).join('')
+            }export {${
+              depLoad.a[1].map(
+                expt => expt.ln ? `${expt.ln} as ${depLoad.S.slice(expt.s, expt.e)}` : `d$_ as default`
```
Comment (guybedford) [inline src/es-module-shims.js:284]: Default should work out naturally, we shouldn't need to branch on it anymore?

**Review by guybedford — COMMENTED** [review]
Getting there, see last comments.

**Comment by guybedford** [comment]
This seems to be failing on Chrome 695079. I'd advise trying to download that version from https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F695079%2Fchrome-win.zip?alt=media to test locally why its failing!

**Comment by guybedford** [comment]
Firefox 67 also seems to have an issue.

**Comment by tommie** [comment]
Since this is only failing on some browsers, I propose #313 to have some feedback in the logs.

There also seems to be some infrastructure errors comingled:

```
Spawning browser: /opt/hostedtoolcache/firefox/67.0/x64/firefox -headless
Retrying...
Spawning browser: /opt/hostedtoolcache/firefox/67.0/x64/firefox -headless
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn /opt/hostedtoolcache/firefox/67.0/x64/firefox ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
...
```

It's in `onexit`, so it's probably trying to wait twice on the old browser process. Or something. I don't know if Karma provides more feedback on these types of issues. Maybe.

File: src/es-module-shims.js (hunk 4 above)
Comment (tommie) [reply src/es-module-shims.js]: I don't understand how. We still need to export `default`, but it doesn't have an `ln`, right?

Moved the `expr.ln` conditional to a `map()` ahead of the template expansion.

File: src/es-module-shims.js (hunk 3 above)
Comment (tommie) [reply src/es-module-shims.js]: Why don't we have to proxy-export the default (which doesn't have a local name)?

File: src/es-module-shims.js (hunk 4 above)
Comment (guybedford) [reply src/es-module-shims.js]: This is just an _early_ export process to help with during-execution accesses - the main cycle update function is called after execution with the full namespace, which would have the default and reexported bindings as well.

File: src/es-module-shims.js [hunk 5]
```diff
@@ -267,15 +267,18 @@ function resolveDeps (load, seen) {
         if (cycleShell) {
           // circular shell creation
           if (!(blobUrl = depLoad.s)) {
+            function dotOrBracketAccessor(expt) {
+              const ch = depLoad.S[expt.s];
+              return (ch === '"' || ch === "'") ? `[${depLoad.S.slice(expt.s, expt.e)}]` : '.' + expt.n;
+            }
+            const shellExports = depLoad.a[1].map(expt => expt.ln ? expt : {...expt, ln: 'd$_'});
```
Comment (guybedford) [inline src/es-module-shims.js:274]: For early default updates, we should instead explicitly detect `expt.n === 'default'`.

**Review by guybedford — COMMENTED** [review]
Getting there! Note that nothing will beat the debugging experience of actually running the failing browsers to fix the tests!

File: src/es-module-shims.js (hunk 5 above)
Comment (guybedford) [reply src/es-module-shims.js:274]: I still don't see how we would update the default without a local name though... I'm pretty sure it's a moot point.

**Comment by tommie** [comment]
> Getting there! Note that nothing will beat the debugging experience of actually running the failing browsers to fix the tests!

Well, if I can avoid messing with browser installations, I will. I'm testing this locally on Chrome 103, FWIW.

* Chrome 69 (?) fails with `Fail Circular dependencies should support shell update import interleaving: Unexpected string`
* Firefox 67 says `Fail Circular dependencies should support shell update import interleaving: missing export name`

Those look like real errors, so perhaps it is time to download some older versions.

File: src/es-module-shims.js (hunk 5 above)
Comment (guybedford) [reply src/es-module-shims.js]: I went ahead and added the ordered binding approach discussed previously!

**Comment by guybedford** [comment]
The remaining issue seems to be that quoted exports aren't supported in older browsers. I think the best approach for now is just to leave these cases out of the tests since this isn't polyfillable.

**Comment by tommie** [comment]
Cool. Thank you so much for maintaining this project, and finishing the PR!

I just wanted import maps to work in Firefox, and being able to simply import a polyfill is awesome.

**Comment by guybedford** [comment]
Thanks again for working on this one, has been a huge help.
